In [1]:
import numpy as np
from sklearn import datasets
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [2]:
diabetes= datasets.load_diabetes()
#dataset is in array format

In [3]:
diabetes.data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [4]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [5]:
ridge=Ridge()

In [6]:
#defining hyperparameters
alphas = np.array([1,0.1,0.01,0.001,0.0001,0])

In [7]:
#using gridsearchcv
grid = GridSearchCV(estimator=ridge, param_grid=dict(alpha=alphas))
#fitting the data
grid.fit(diabetes.data, diabetes.target)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([1.e+00, 1.e-01, 1.e-02, 1.e-03, 1.e-04, 0.e+00])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [8]:
print(grid.best_score_)

0.48879020446060156


In [9]:
print(grid.best_params_)

{'alpha': 0.001}


In [10]:
iris = datasets.load_iris()

In [11]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [12]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
from sklearn import svm
svc=svm.SVC()

In [14]:
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

In [15]:
grid_1 = GridSearchCV(estimator=svc, param_grid=parameters)
grid_1.fit(iris.data,iris.target)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1, 10], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [16]:
print(grid_1.best_score_)

0.98


In [17]:
print(grid_1.best_params_)

{'C': 1, 'kernel': 'linear'}


In [18]:
### cross validation and GrisdsearchCV on red wine dataset ###

In [19]:
import pandas as pd

In [20]:
wine=pd.read_csv('winequality-red.csv')

In [21]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [22]:
wine.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [23]:
X=wine.iloc[:,0:-1]
y=wine.iloc[:,-1]

In [24]:
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [25]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [26]:
#since we will use CV ,no need to define test size
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=0)

In [27]:
from sklearn.preprocessing import StandardScaler
feature_scaler = StandardScaler()
X_train = feature_scaler.fit_transform(X_train)
X_test = feature_scaler.transform(X_test)

In [28]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=300, random_state=0)

In [29]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(estimator=rf, X=X_train, y=y_train, cv=5,scoring='accuracy')

In [30]:
print(scores)
print(scores.mean())
print(scores.std())

[0.64049587 0.63636364 0.68049793 0.70168067 0.68220339]
0.6682482983085702
0.025492550433144235


In [31]:
#Gridsearchcv
#defining hyperparameters
grid_param = {
    'n_estimators': [100, 300, 500, 800, 1000],
    'criterion': ['gini', 'entropy'],
    'bootstrap': [True, False]
}

In [32]:
grid_2 = GridSearchCV(estimator=rf,
                     param_grid=grid_param,
                     scoring='accuracy',
                     cv=5,
                     n_jobs=-1)

In [33]:
grid_2.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators=300, n_jobs=None,
                                              oob_score=False, random_state=0,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'bootst

In [34]:
print(grid_2.best_params_)
print(grid_2.best_score_)

{'bootstrap': True, 'criterion': 'entropy', 'n_estimators': 1000}
0.6747289407839867


In [35]:
#griscearchcv on breast cancer dataset#

In [38]:
data = pd.read_csv("ionosphere_csv.csv")

In [39]:
data

a01  a02      a03      a04      a05      a06      a07      a08      a09  \
0      1    0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1      1    0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2      1    0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3      1    0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4      1    0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   
5      1    0  0.02337 -0.00592 -0.09924 -0.11949 -0.00763 -0.11824  0.14706   
6      1    0  0.97588 -0.10602  0.94601 -0.20800  0.92806 -0.28350  0.85996   
7      0    0  0.00000  0.00000  0.00000  0.00000  1.00000 -1.00000  0.00000   
8      1    0  0.96355 -0.07198  1.00000 -0.14333  1.00000 -0.21313  1.00000   
9      1    0 -0.01864 -0.08459  0.00000  0.00000  0.00000  0.00000  0.11470   
10     1    0  1.00000  0.06655  1.00000 -0.18388  1.00000 -0.27320  1.00000   
11     1    0  1.00000 -0.54210  1.00000 -1.00000  1.00000 -1.00000  1.00000   
12     1    0  1.00000 -0.16316  1.00000 -0.10169  0.99999 -0.15197  1.00000   
13     1    0  1.00000 -0.86701  1.00000  0.22280  0.85492 -0.39896  1.00000   
14     1    0  1.00000  0.07380  1.00000  0.03420  1.00000 -0.05563  1.00000   
15     1    0  0.50932 -0.93996  1.00000  0.26708 -0.03520 -1.00000  1.00000   
16     1    0  0.99645  0.06468  1.00000 -0.01236  0.97811  0.02498  0.96112   
17     0    0  0.00000  0.00000 -1.00000 -1.00000  1.00000  1.00000 -1.00000   
18     1    0  0.67065  0.02528  0.66626  0.05031  0.57197  0.18761  0.08776   
19     0    0  1.00000 -1.00000  0.00000  0.00000  0.00000  0.00000  1.00000   
20     1    0  1.00000 -0.00612  1.00000 -0.09834  1.00000 -0.07649  1.00000   
21     0    0  1.00000  1.00000  0.00000  0.00000  0.00000  0.00000 -1.00000   
22     1    0  0.96071  0.07088  1.00000  0.04296  1.00000  0.09313  0.90169   
23     0    0 -1.00000  1.00000  0.00000  0.00000  0.00000  0.00000 -1.00000   
24     1    0  1.00000 -0.06182  1.00000  0.02942  1.00000 -0.05131  1.00000   
25     1    0  1.00000  0.57820  1.00000 -1.00000  1.00000 -1.00000  1.00000   
26     1    0  1.00000 -0.08714  1.00000 -0.17263  0.86635 -0.81779  0.94817   
27     0    0 -1.00000 -1.00000  0.00000  0.00000 -1.00000  1.00000  1.00000   
28     1    0  1.00000  0.08380  1.00000  0.17387  1.00000 -0.13308  0.98172   
29     0    0 -1.00000 -1.00000  1.00000  1.00000  1.00000 -1.00000 -1.00000   
..   ...  ...      ...      ...      ...      ...      ...      ...      ...   
321    1    0  0.89505 -0.03168  0.87525  0.05545  0.89505  0.01386  0.92871   
322    1    0  0.90071  0.01773  1.00000 -0.01773  0.90071  0.00709  0.84752   
323    1    0  0.39394 -0.24242  0.62655  0.01270  0.45455  0.09091  0.63636   
324    1    0  0.86689  0.35950  0.72014  0.66667  0.37201  0.83049  0.08646   
325    1    0  0.89563  0.37917  0.67311  0.69438  0.35916  0.88696 -0.04193   
326    1    0  0.90547  0.41113  0.65354  0.74761  0.29921  0.95905 -0.13342   
327    1    0  1.00000  1.00000  0.36700  0.06158  0.12993  0.92713 -0.27586   
328    1    0  1.00000  0.51515  0.45455  0.33333  0.06061  0.36364 -0.32104   
329    1    0  0.88110  0.00000  0.94817 -0.02744  0.93598 -0.01220  0.90244   
330    1    0  0.82624  0.08156  0.79078 -0.08156  0.90426 -0.01773  0.92908   
331    1    0  0.74468  0.10638  0.88706  0.00982  0.88542  0.01471  0.87234   
332    1    0  0.87578  0.03727  0.89951  0.00343  0.89210  0.00510  0.86335   
333    1    0  0.97513  0.00710  0.98579  0.01954  1.00000  0.01954  0.99290   
334    1    0  1.00000  0.01105  1.00000  0.01105  1.00000  0.02320  0.99448   
335    1    0  1.00000 -0.01342  1.00000  0.01566  1.00000 -0.00224  1.00000   
336    1    0  0.88420  0.36724  0.67123  0.67382  0.39613  0.86399  0.02424   
337    1    0  0.90147  0.41786  0.64131  0.75725  0.30440  0.95148 -0.20449   
338    1    0  0.32789  0.11042  0.15970  0.29308  0.14020  0.74485 -0.25131   
339  

In [40]:
data.shape

(351, 35)

In [41]:
data.head()

a01  a02      a03      a04      a05      a06      a07      a08      a09  \
0    1    0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1    1    0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2    1    0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3    1    0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4    1    0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

       a10  ...      a26      a27      a28      a29      a30      a31  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

       a32      a33      a34  class  
0 -0.54487  0.18641 -0.45300      g  
1 -0.06288 -0.13738 -0.02447      b  
2 -0.24180  0.56045 -0.38238      g  
3  1.00000 -0.32382  1.00000      b  
4 -0.59573 -0.04608 -0.65697      g  

[5 rows x 35 columns]

In [42]:
data.tail()

a01  a02      a03      a04      a05      a06      a07      a08      a09  \
346    1    0  0.83508  0.08298  0.73739 -0.14706  0.84349 -0.05567  0.90441   
347    1    0  0.95113  0.00419  0.95183 -0.02723  0.93438 -0.01920  0.94590   
348    1    0  0.94701 -0.00034  0.93207 -0.03227  0.95177 -0.03431  0.95584   
349    1    0  0.90608 -0.01657  0.98122 -0.01989  0.95691 -0.03646  0.85746   
350    1    0  0.84710  0.13533  0.73638 -0.06151  0.87873  0.08260  0.88928   

         a10  ...      a26      a27      a28      a29      a30      a31  \
346 -0.04622  ... -0.04202  0.83479  0.00123  1.00000  0.12815  0.86660   
347  0.01606  ...  0.01361  0.93522  0.04925  0.93159  0.08168  0.94066   
348  0.02446  ...  0.03193  0.92489  0.02542  0.92120  0.02242  0.92459   
349  0.00110  ... -0.02099  0.89147 -0.07760  0.82983 -0.17238  0.96022   
350 -0.09139  ... -0.15114  0.81147 -0.04822  0.78207 -0.00703  0.75747   

         a32      a33      a34  class  
346 -0.10714  0.90546 -0.04307      g  
347 -0.00035  0.91483  0.04712      g  
348  0.00442  0.92697 -0.00577      g  
349 -0.03757  0.87403 -0.16243      g  
350 -0.06678  0.85764 -0.06151      g  

[5 rows x 35 columns]

In [43]:
X=data.iloc[:,:-1].values

In [44]:
X.shape

(351, 34)

In [45]:
y=data.iloc[:,-1].values

In [46]:
y.shape

(351,)

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [53]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [54]:
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)

In [55]:
from sklearn.metrics import accuracy_score,recall_score,precision_score,f1_score,confusion_matrix

In [56]:
print(accuracy_score(y_test,y_pred))

0.8636363636363636


In [57]:
print(recall_score(y_test,y_pred))

0.9821428571428571


In [58]:
print(precision_score(y_test,y_pred))

0.8333333333333334


In [59]:
print(f1_score(y_test,y_pred))

0.9016393442622951


In [60]:
print(confusion_matrix(y_test,y_pred))

[[21 11]
 [ 1 55]]


In [61]:
#GridsearchCV
grid_values = {'penalty': ['l1', 'l2'],'C':[0.001,.009,0.01,.09,1,5,10,25]}
grid_3 = GridSearchCV(lr, param_grid = grid_values,scoring = 'recall')
grid_3.fit(X_train, y_train)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='warn',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='warn',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.009, 0.01, 0.09, 1, 5, 10, 25],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='recall', verbose=0)

In [64]:
print(grid_3.best_params_)
print(grid_3.best_score_)

{'C': 0.001, 'penalty': 'l2'}
1.0


In [65]:
y_grdpred = grid_3.predict(X_test)

In [66]:
print(accuracy_score(y_test,y_grdpred))

0.6477272727272727


In [67]:
print(precision_score(y_test,y_grdpred))

0.6436781609195402


In [68]:
print(f1_score(y_test,y_grdpred))

0.7832167832167831


In [69]:
print(confusion_matrix(y_test,y_grdpred))

[[ 1 31]
 [ 0 56]]
